### ISSUE TITLE
Сервис событий

### ISSUE THREAD

**Issue by bupyc9** [worksolutions/bitrix-module-tools#24]
```php
$module = \WS\Tools\Module::getInstance();
$eventManager = $module->eventManager();
$eventType = \WS\Tools\Events\EventType::create(\WS\Tools\Events\EventType::IBLOCK_AFTER_IBLOCK_ELEMENT_DELETE);
```
Если в метод "subscribe", сервиса, вторым аргументом передавать экземпляр объекта класса "CustomHandler", тогда обработчик - не работает.
Если передавать массив, согласно [пункту 3](https://github.com/worksolutions/bitrix-module-tools#3-%D0%A0%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D1%81%D1%82%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B3%D0%BE-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%B0-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0), тогда обработчик - работает

**Comment by bupyc9** [comment]
версия php 5.6

**Comment by DsXack** [comment]
Решено в a9e9df68826d1e9ee43bc18d139a315ca9b2d70e
