### ISSUE TITLE
Сервис работы с кэшем

### ISSUE THREAD

**Issue by sokolovsky** [worksolutions/bitrix-module-tools#4]

**Comment by bupyc9** [comment]
В новом ядре, есть класс Bitrix\Main\Data\Cache

**Comment by sokolovsky** [comment]
Ситуация в корне не очень изменилась, в поставке методы:
* startDataCache
* abortDataCache
* endDataCache
* isCacheExpired
* clearCache
Их много и делают все как и раньше, единственное некоторые параметры инкапсулируют

Единственное отличие, движок хранения данных можно назначить 

Предлагаю:
Определить менеджера кэшей, движки берем у битрикса. Менеджер владеет двумя типами кэшей: параметры и контент.

```php
/* @var $cache WS\Tools\ContentCache */
$cache = $cacheManager->getContentCache('some_cache_in_page', $timeLive);
$cache->getContent();
$cache->hasContent();
$cache->setContent($comtent);

/* @var $cache WS\Tools\ParamsCache */
$cache = $cacheManager->getParamsCache('some_params', $timeLive);
$data = $cache->getData();
$cache->setData(array('one', 'two'));
```
@bupyc9, @DsXack Ваши предложения?

**Comment by DsXack** [comment]
Как кеш параметров взаимодействует с кешем контента? В коде не увидел.

**Comment by sokolovsky** [comment]
Никак. Это разные приемы кэширования.

**Comment by DsXack** [comment]
Переименовали `\WS\Tools\DataCache` в `\WS\Tools\ArrayCache`

**Comment by DsXack** [comment]
Нужно описать инциализацию менеджера кеширования, используя различные адапторы кеширования битрикса
